USE RETAIL;

SELECT * FROM CUSTOMER;
SELECT * FROM CATEGORY;
SELECT * FROM PRODUCT;
SELECT * FROM ORDERS;
SELECT * FROM SUPPLIER;

INSERT INTO CUSTOMER (FULLNAME, EMAIL, PHONE, ADDRESS) VALUES ('Fiona Dsouza', 'fiona@example.com', '9123456789', '22 Mango Street'), ('George Mehta', 'george@example.com', NULL, '88 Rose Avenue'), ('Hema Sharma', 'hema@example.com', '9090909090', '55 Lotus Lane');
INSERT INTO CATEGORY (CATNAME) VALUES('Toys'), ('Beauty'), ('Stationery');
INSERT INTO SUPPLIER (SUPNAME, SUPEMAIL) VALUES ('ToyHouse Ltd.', 'support@toyhouse.com'), ('GlowUp Essentials', NULL), ('PaperTree Supplies', 'hello@papertree.com');
INSERT INTO PRODUCT (PRODNAME, PRICE, STOCK, CATID, SUPID) VALUES ('Lego Set', 999.00, 25, 6, 6), ('Face Cream', 249.00, 40, 7, 7), ('Notebook Pack', 149.00, NULL, 8, 8);
INSERT INTO ORDERS (CUSTID, ORDERDATE, PRODID, QTY, AMT) VALUES (6, '2025-06-23', 6, 1, 999.00), (7, '2025-06-23', 7, 2, 498.00), (8, '2025-06-24', 8, 3, 447.00);

SELECT * FROM CUSTOMER;
SELECT * FROM CATEGORY;
SELECT * FROM PRODUCT;
SELECT * FROM ORDERS;
SELECT * FROM SUPPLIER;

UPDATE PRODUCT SET PRICE = 289.00 WHERE PRODNAME = 'Face Cream';
UPDATE CUSTOMER SET ADDRESS = 'New Residency Block 2' WHERE FULLNAME = 'Hema Sharma';
UPDATE ORDERS SET QTY = 4, AMT = 596.00 WHERE CUSTID = 8 AND PRODID = 8;

SELECT * FROM CUSTOMER;
SELECT * FROM CATEGORY;
SELECT * FROM PRODUCT;
SELECT * FROM ORDERS;
SELECT * FROM SUPPLIER;

DELETE FROM CUSTOMER WHERE PHONE IS NULL;
DELETE FROM SUPPLIER WHERE SUPID = 2;
DELETE FROM ORDERS WHERE PRODID = 8;
DELETE FROM PRODUCT WHERE PRODID = 8;

SELECT * FROM CUSTOMER;
SELECT * FROM CATEGORY;
SELECT * FROM PRODUCT;
SELECT * FROM ORDERS;
SELECT * FROM SUPPLIER;
